### ISSUE TITLE
Ghost container cannot create a right connection to db using docker compose.

### ISSUE THREAD

**Issue by kingcc** [TryGhost/Ghost-CLI#856]
I would not understand why to use '%' instead of 'DB host' fields to build a connection. (#644)

When i used docker compose to link two containers(ghost and mysql) with two compose files(One network), knex migrate got wrong ip address from '%':

The ghost compose file:

```
version: '3'
services:
  blog:
    image: ghost:1-alpine
    restart: always
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
networks:
  default:
    external:
      name: one-network
```

The db compose file:

```
version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
networks:
  default:
    external:
      name: one-network
```

When starting ghost, some error occurs:

```sh
$ docker logs --tail=16 blog
Access denied for user 'root'@'192.168.112.9' # ip of db which right is 192.168.112.8
```

Sincerely
